  // =========================================================================
  // Der Ton
  // =========================================================================
  // Motorklang aus Zuendereignissen (nach ange-yaghi/engine-sim, MIT), die
  // geschnittenen Schleifen, Einmal-Effekte und die Streckenkulisse.
  //
  // Woher jede Datei kommt, steht in audio/CREDITS.md - synthetisch gegen aus
  // Aufnahmen geschnitten, und das wird auseinandergehalten.

  // ---- Synthesized engine sound (Web Audio API, no external audio files — avoids any
  // question of reusing the real game's actual audio assets) ----
  let audioCtx = null, engineOsc = null, engineGain = null;
  let soundEnabled = true; // checkbox is checked by default now

  function initEngineSound() {
    if (audioCtx) return;
    audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    engineOsc = audioCtx.createOscillator();
    engineOsc.type = soundProfile.wave;
    engineOsc.frequency.value = soundProfile.baseFreq;
    engineGain = audioCtx.createGain();
    engineGain.gain.value = 0;
    engineOsc.connect(engineGain).connect(audioCtx.destination);
    engineOsc.start();
  }

  // Browsers refuse to start audio without a user gesture, so even though sound is on by
  // default we can only actually create the AudioContext once the user interacts. This
  // one-shot listener does it on the very first click/keypress anywhere in the app.
  function unlockAudioOnFirstGesture() {
    if (soundEnabled) {
      initEngineSound();
      if (audioCtx.state === 'suspended') audioCtx.resume();
      loadEngineSamples(); // needs the AudioContext, so it can only start from here
      loadFxSamples();
      loadAmbience();
    }
    document.removeEventListener('pointerdown', unlockAudioOnFirstGesture);
    document.removeEventListener('keydown', unlockAudioOnFirstGesture);
  }
  document.addEventListener('pointerdown', unlockAudioOnFirstGesture);
  document.addEventListener('keydown', unlockAudioOnFirstGesture);

  $('sound-enable').addEventListener('change', (e) => {
    soundEnabled = e.target.checked;
    if (soundEnabled) {
      initEngineSound(); // lazy-start on this user gesture, per browser autoplay policy
      if (audioCtx.state === 'suspended') audioCtx.resume();
      loadEngineSamples();
      loadFxSamples();
      loadAmbience();
      refreshAmbienceGains();
    } else if (engineGain) {
      refreshAmbienceGains();
      engineGain.gain.setTargetAtTime(0, audioCtx.currentTime, 0.05);
      if (sampleEngine.master) sampleEngine.master.gain.setTargetAtTime(0, audioCtx.currentTime, 0.05);
    }
  });

  // Der ERSATZMOTOR, seit v0.5 nicht mehr im Menue. Vier Oszillator-Charaktere, live
  // erzeugt, ohne Datei - und genau deshalb bleiben sie: per file:// ohne den Ordner audio/
  // sind sie die einzige Tonquelle, und ein Auto, das lautlos fährt, sieht kaputt aus.
  //
  // Waehlbar sind sie nicht mehr. Wer sie hoert, hoert einen Rueckfall, und der wird jetzt
  // protokolliert statt still zu passieren: dass er still war, hat den Porsche-Fehler
  // vier Wochen lang versteckt.
  const SOUND_PROFILES = {
    v8:    { wave: 'sawtooth', baseFreq: 50,  freqSpan: 190, gainBase: 0.03, gainSpan: 0.13 },
    v10:   { wave: 'sawtooth', baseFreq: 110, freqSpan: 520, gainBase: 0.02, gainSpan: 0.11 },
    ev:    { wave: 'sine',     baseFreq: 180, freqSpan: 900, gainBase: 0.01, gainSpan: 0.09 },
    turbo: { wave: 'square',   baseFreq: 60,  freqSpan: 240, gainBase: 0.02, gainSpan: 0.12 },
  };
  let soundProfile = SOUND_PROFILES.v8;

  // ---- Sample-based engine ----
  // Three looping buffers per car (idle/mid/high), pitch-shifted by playbackRate and
  // crossfaded by RPM. The loops are fully synthetic — generated by tools/engine_synth.py
  // from a firing-event model, no recorded material — see audio/CREDITS.md.
  const SAMPLE_CARS = [
    // NEUN GERECHNETE MOTOREN, und jeder gehoert zu einem wirklichen Auto.
    //
    // Bis v0.4.52 waren es siebzehn: acht Rennmotoren nach technischen Angaben, sechs
    // generische (ein Strassen-Porsche, ein Turbo-Reihensechser, ein Flat-Plane-V8, ein
    // V10, ein Dreizylinder, ein V12-Formel-1) und zwei Aufnahmen. Das waren 68
    // Schleifendateien, von denen die meisten kein Auto benannten, das man kennt.
    //
    // Geblieben sind die acht nach Angaben gerechneten, der Mustang - der ist ebenfalls
    // gerechnet, siehe audio/CREDITS.md - und neu ein Formel 1 nach dem Reglement 2026.
    // Die zwei Aufnahmen sind mit heraus; damit ist ALLES hier synthetisch, und der
    // Unterschied, den CREDITS.md aufmacht, betrifft nur noch die Umgebungsgeraeusche.
    'amggt3', 'c6r', 'z06gt3r', 'vantagegt3', 'm4gt3', 'f296gt3', 'huracan', 'p992gt3r',
    'mustang', 'f1_2026',
  ];
  const BANDS = ['idle', 'mid', 'high'];
  let engineVolume = 0.7;
  const sampleEngine = { buffers: {}, rpmScale: {}, nodes: null, over: null, car: null,
                         master: null, ready: false, loading: false };

  async function loadEngineSamples() {
    if (sampleEngine.ready || sampleEngine.loading || !audioCtx) return;
    sampleEngine.loading = true;
    try {
      // cache: 'reload' nur fuer das Verzeichnis, nicht fuer die Tondateien. Die Datei ist
      // zwei Kilobyte, die Toene sind Megabytes - und ein veraltetes Verzeichnis laesst
      // Funktionen still verschwinden, statt einen Fehler zu zeigen. Genau das ist zweimal
      // passiert: ein zwischengespeichertes loops.json ohne die neuen Motoren und ein
      // fx.json ohne die Hupen. In beiden Faellen sah es wie ein Fehler im Code aus.
      const res = await fetch('audio/loops.json', { cache: 'reload' });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      const manifest = await res.json();
      for (const car of Object.keys(manifest)) {
        sampleEngine.buffers[car] = {};
        // Optional per-car transposition. Needed for the sampled cars: the Corvette
        // recording only reaches about 4500/min, while the app revs to 9000, so without a
        // factor the top loop was played back at 1.99x - right against the clamp - and the
        // whole engine sounded an octave too high. A synthesised engine does not need this
        // because its loops are generated at whatever rpm is asked for.
        sampleEngine.rpmScale[car] = manifest[car].rpmScale || 1;
        // 'over' is the closed-throttle loop and is OPTIONAL: the Corvette profile is cut
        // from a recording that has no overrun material, so its absence must not fail the
        // load. Everything the generator makes has one.
        for (const band of BANDS.concat(['over'])) {
          const loop = manifest[car].loops[band];
          if (!loop) continue;
          const r = await fetch('audio/' + loop.file);
          if (!r.ok) throw new Error(loop.file);
          sampleEngine.buffers[car][band] = {
            buffer: await audioCtx.decodeAudioData(await r.arrayBuffer()),
            baseRpm: loop.baseRpm,
          };
        }
      }
      sampleEngine.ready = true;
      log('Motorsamples geladen: ' + Object.keys(manifest).join(', '), 'info');
      const sel = $('sound-profile').value;
      if (SAMPLE_CARS.includes(sel)) startSampleEngine(sel);
    } catch (err) {
      // Entirely expected wherever audio/ is not deployed. The synthesized engine keeps
      // working, so this must NOT surface as an error the user has to react to.
      sampleEngine.ready = false;
      log('Keine Motorsamples gefunden, synthetischer Motor bleibt aktiv.', 'info');
    }
    sampleEngine.loading = false;
  }

  // ---- One-shot and looping effect samples ----
  const fxBuffers = { crash: [], brake: null, pit: null, pitFuel: null, pitRepair: null,
                      start: {}, shift: {}, horns: {} };
  let brakeNode = null, brakeGain = null;

  async function loadFxSamples() {
    if (!audioCtx) return;
    try {
      const res = await fetch('audio/fx.json', { cache: 'reload' });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      const fx = await res.json();
      const grab = async (file) => {
        const r = await fetch('audio/' + file);
        if (!r.ok) throw new Error(file);
        return audioCtx.decodeAudioData(await r.arrayBuffer());
      };
      fxBuffers.crash = await Promise.all(fx.crash.map(c => grab(c.file)));
      fxBuffers.brake = await grab(fx.brake.file);
      // Duldsam gegenueber einem aelteren audio/: fehlt der Eintrag, bleibt der Ton weg und
      // der Ladevorgang laeuft weiter. Genau daran hing schon einmal der Schaltton.
      if (fx.tyre) fxBuffers.tyre = await grab(fx.tyre.file);
      fxBuffers.pit = await grab(fx.pit.file);
      // Both are loops: they run for as long as their job does. Missing files are tolerated
      // (grab returns null) and the sound is simply absent rather than the load failing.
      if (fx.pit_fuel) fxBuffers.pitFuel = await grab(fx.pit_fuel.file);
      if (fx.pit_repair) fxBuffers.pitRepair = await grab(fx.pit_repair.file);
      // Hupen. Optional, wie die Schubschleifen: ein aelteres audio/ hat sie nicht, und ein
      // fehlender Eintrag darf den ganzen Ladevorgang nicht abbrechen - genau daran hing
      // schon einmal der Schaltton.
      if (fx.horns) {
        for (const k of Object.keys(fx.horns)) fxBuffers.horns[k] = await grab(fx.horns[k].file);
      }
      // Optional: older audio bundles predate the shift sounds, and a missing file must
      // not take the whole effects load down with it.
      if (fx.shift) {
        for (const dir of Object.keys(fx.shift)) fxBuffers.shift[dir] = await grab(fx.shift[dir].file);
      }
      for (const car of Object.keys(fx.start)) fxBuffers.start[car] = await grab(fx.start[car].file);
      log('Effektsounds geladen (' + fxBuffers.crash.length + ' Crash-Varianten).', 'info');
    } catch (err) {
      log('Keine Effektsounds gefunden, synthetische Töne bleiben aktiv.', 'info');
    }
  }

  function playFx(buffer, gainVal) {
    if (!buffer || !audioCtx || !soundEnabled) return false;
    const src = audioCtx.createBufferSource();
    src.buffer = buffer;
    const g = audioCtx.createGain();
    g.gain.value = gainVal === undefined ? 0.9 : gainVal;
    src.connect(g).connect(audioCtx.destination);
    src.start();
    return true;
  }

  // Fuel warning, built like a modern seatbelt reminder rather than like a falling chime.
  // The difference is not decoration: a seatbelt reminder is two SHORT pulses at a FIXED
  // pitch, and that is why it reads as a reminder instead of as an alarm or as a jingle. A
  // falling glide - what this was - reads as "something is winding down", which is wrong for
  // a level that will keep dropping until you do something.
  const FUEL_TONE_HZ = 660;       // squarely in the band a small speaker reproduces
  const FUEL_PULSE_S = 0.075;     // short. A long pulse turns into a note.
  const FUEL_GAP_S = 0.115;
  function fuelPulse(when, gainVal) {
    if (!audioCtx) return;
    const o1 = audioCtx.createOscillator();
    const o2 = audioCtx.createOscillator();
    const g = audioCtx.createGain();
    const g2 = audioCtx.createGain();
    o1.type = 'sine';
    o2.type = 'sine';
    o1.frequency.value = FUEL_TONE_HZ;
    // A fifth above, quietly. One sine alone sounds like a test tone; the interval is what
    // makes it read as a fitted buzzer.
    o2.frequency.value = FUEL_TONE_HZ * 1.5;
    g2.gain.value = 0.3;
    // Soft edges on purpose. A rectangular gate on a sine clicks, and the click is the part
    // people find unpleasant - not the tone.
    g.gain.setValueAtTime(0.0001, when);
    g.gain.exponentialRampToValueAtTime(gainVal, when + 0.008);
    g.gain.setValueAtTime(gainVal, when + FUEL_PULSE_S - 0.012);
    g.gain.exponentialRampToValueAtTime(0.0001, when + FUEL_PULSE_S);
    o1.connect(g);
    o2.connect(g2).connect(g);
    g.connect(audioCtx.destination);
    o1.start(when); o2.start(when);
    o1.stop(when + FUEL_PULSE_S + 0.02);
    o2.stop(when + FUEL_PULSE_S + 0.02);
  }

  // One double pulse at 20 %, two at 10 %. The COUNT carries the urgency, so the driver does
  // not have to look away from the track to learn which mark went by.
  function playFuelWarning(count) {
    if (!audioCtx || !soundEnabled) return;
    let t = audioCtx.currentTime + 0.02;
    for (let i = 0; i < count; i++) {
      fuelPulse(t, 0.26);
      fuelPulse(t + FUEL_PULSE_S + FUEL_GAP_S, 0.26);
      t += 2 * (FUEL_PULSE_S + FUEL_GAP_S) + 0.16;   // a beat of silence between groups
    }
  }

  // Picking at random matters: a series of contacts with one identical sample reads as a
  // glitch rather than as several separate impacts.
  function playCrashFx() {
    if (!fxBuffers.crash.length) return false;
    const i = Math.floor(Math.random() * fxBuffers.crash.length);
    return playFx(fxBuffers.crash[i], 0.95);
  }

  // The brake squeal is a sustained loop faded by pressure, the way a real squeal swells
  // and dies rather than being retriggered.
  // Pneumatic paddle shift. Up and down are distinct samples because they really do
  // sound different — the downshift carries a longer air release. If the samples are
  // missing, a two-tone stands in rather than nothing happening at all.
  function playShiftSound(direction) {
    const buf = direction >= 0 ? fxBuffers.shift.up : fxBuffers.shift.down;
    if (playFx(buf, 0.35)) return;   // quieter: the shift should be felt, not announced
    const f = direction >= 0 ? 900 : 620;
    playTone(f, 0.05, 'square', 0.06);
    setTimeout(() => playTone(f * 0.6, 0.05, 'triangle', 0.05), 35);
  }

  function setBrakeSqueal(amount) {
    if (!fxBuffers.brake || !audioCtx || !soundEnabled) return;
    if (amount > 0.01 && !brakeNode) {
      brakeNode = audioCtx.createBufferSource();
      brakeNode.buffer = fxBuffers.brake;
      brakeNode.loop = true;
      brakeGain = audioCtx.createGain();
      brakeGain.gain.value = 0;
      brakeNode.connect(brakeGain).connect(audioCtx.destination);
      brakeNode.start();
    }
    if (!brakeGain) return;
    // Eigener Regler, nicht mehr engineVolume. Es hing am Motorregler, und damit war das
    // Quietschen nur zusammen mit dem Motor leiser zu bekommen - also gar nicht.
    // Vorgabe 0,6, also etwas leiser als die 1,0, die es faktisch vorher hatte.
    brakeGain.gain.setTargetAtTime(Math.min(0.25, amount * 0.25) * brakeVolume,
                                   audioCtx.currentTime, 0.06);
    if (amount <= 0.01 && brakeNode) {
      const node = brakeNode;
      brakeNode = null; brakeGain = null;
      setTimeout(() => { try { node.stop(); } catch (e) { /* already stopped */ } }, 400);
    }
  }

  // ---- Reifenquietschen am Grenzbereich ------------------------------------------------
  //
  // Nach dem Muster des Bremsenquietschens: eine gehaltene Schleife, deren Lautstaerke
  // eingeblendet wird - so wie ein echtes Quietschen anschwillt und abklingt, statt neu
  // angestossen zu werden.
  //
  // ZWEI UNTERSCHIEDE zum Bremsenquietschen, und beide sind Absicht:
  //
  // 1. Die TONHOEHE laeuft mit. Ein Reifen wird hoeher, wenn er sich der Grenze naehert.
  //    Umgesetzt ueber playbackRate und nicht als Sweep in der Datei: ein eingebackener
  //    Sweep wuerde gegen die Modulation arbeiten und die Naht der Schleife hoerbar machen.
  //
  // 2. Es setzt erst SPAET ein, bei 85 Prozent Ausnutzung. Ein Quietschen, das bei jeder
  //    Kurve mitlaeuft, ist ein Dauergeraeusch und keine Rueckmeldung - und die Aussage
  //    "du bist am Limit" ist nur etwas wert, wenn sie nicht immer gilt.
  let tyreNode = null, tyreGain = null;
  const TYRE_SQUEAL_START = 0.85;
  function setTyreSqueal(nutzung) {
    if (!fxBuffers.tyre || !audioCtx || !soundEnabled) return;
    // Unterhalb der Schwelle auf null abbilden, statt die Schwelle im Nenner zu vergessen:
    // sonst faengt es bei 0 an und ist bei 0,85 schon laut.
    const roh = (Math.max(0, Math.min(1.2, nutzung)) - TYRE_SQUEAL_START)
                / (1 - TYRE_SQUEAL_START);
    const menge = Math.max(0, Math.min(1, roh));
    if (menge > 0.01 && !tyreNode) {
      tyreNode = audioCtx.createBufferSource();
      tyreNode.buffer = fxBuffers.tyre;
      tyreNode.loop = true;
      tyreGain = audioCtx.createGain();
      tyreGain.gain.value = 0;
      tyreNode.connect(tyreGain).connect(audioCtx.destination);
      tyreNode.start();
    }
    if (!tyreGain) return;
    tyreGain.gain.setTargetAtTime(Math.min(0.3, menge * 0.3) * tyreVolume,
                                  audioCtx.currentTime, 0.05);
    // 1,0 bis 1,18: hoerbar, aber ohne dass der Ton nach Bandgeschwindigkeit klingt. Mehr
    // verschiebt auch die Schleifenlaenge und macht die Naht hoerbar.
    if (tyreNode) {
      tyreNode.playbackRate.setTargetAtTime(1 + 0.18 * menge, audioCtx.currentTime, 0.08);
    }
    if (menge <= 0.01 && tyreNode) {
      const node = tyreNode;
      tyreNode = null; tyreGain = null;
      setTimeout(() => { try { node.stop(); } catch (e) { /* schon gestoppt */ } }, 400);
    }
  }

  // ---- Ambience: a quiet bed plus scattered one-off events ----
  // Two beds (trackside, rain) loop continuously behind their own gains, and a single timer
  // sprinkles pass-bys and thunder at random intervals. A lone loop, however long, becomes
  // recognisable within minutes; scattered distinct events do not.
  const ambience = { bed: null, rainBed: null, passby: [], thunder: [],
                     bedNode: null, bedGain: null, rainNode: null, rainGain: null,
                     ready: false, rainOn: false, rainLevel: 0, busy: false };
  let ambienceVolume = 0.10;   // track bed and pass-bys: quiet, the engine leads
  let rainVolume = 0.25;
  // Eigene Lautstaerke fuer das Bremsenquietschen. Sie hing vorher an engineVolume.
  // 0,3 statt 0,6: halbiert. Der Startwert steht hier UND im Markup - zwei Orte fuer
  // eine Zahl, und beim Nachziehen muessen beide mit. Genau diese Klasse hat bei den
  // Voreinstellungen siebzehn Abweichungen ergeben.
  let brakeVolume = 0.3;       // rain and thunder: own control, weather stays audible
  // Eigene Lautstaerke, aus demselben Grund wie beim Bremsenquietschen: an engineVolume
  // gehaengt liesse es sich nur zusammen mit dem Motor leiser stellen, also gar nicht.
  // Der Startwert steht hier UND im Markup - beim Nachziehen muessen beide mit.
  let tyreVolume = 0.35;
  let ambienceEnabled = true;   // on, but quiet enough to sit under the engine

  async function loadAmbience() {
    if (ambience.ready || !audioCtx) return;
    try {
      const res = await fetch('audio/ambience.json');
      if (!res.ok) throw new Error('HTTP ' + res.status);
      const m = await res.json();
      const grab = async (file) => {
        const r = await fetch('audio/' + file);
        if (!r.ok) throw new Error(file);
        return audioCtx.decodeAudioData(await r.arrayBuffer());
      };
      ambience.bed = await grab(m.bed.file);
      ambience.passby = await Promise.all((m.passby || []).map(p => grab(p.file)));
      if (m.rain && m.rain.bed) {
        ambience.rainBed = await grab(m.rain.bed.file);
        ambience.thunder = await Promise.all((m.rain.thunder || []).map(t => grab(t.file)));
      }
      ambience.ready = true;
      startAmbienceBeds();
      scheduleAmbienceEvent();
      log('Ambience geladen (' + ambience.passby.length + ' Vorbeifahrten, '
          + ambience.thunder.length + ' Donner).', 'info');
    } catch (err) {
      // Expected wherever audio/ is not deployed — stay silent, exactly like the engines.
      ambience.ready = false;
      log('Keine Ambience gefunden.', 'info');
    }
  }

  function loopBed(buffer, gainVal) {
    const src = audioCtx.createBufferSource();
    src.buffer = buffer;
    src.loop = true;
    const g = audioCtx.createGain();
    g.gain.value = gainVal;
    src.connect(g).connect(audioCtx.destination);
    src.start();
    return { src, g };
  }

  function stopAmbienceBeds() {
    // Muting is not enough — a looping source keeps running for as long as the page lives,
    // and a page can easily outlive the user's attention in a background tab. So tear the
    // nodes down; startAmbienceBeds() rebuilds them when the switch goes back on.
    for (const key of ['bedNode', 'rainNode']) {
      if (ambience[key]) {
        try { ambience[key].stop(); } catch (e) { /* already stopped */ }
        try { ambience[key].disconnect(); } catch (e) { /* not connected */ }
        ambience[key] = null;
      }
    }
    ambience.bedGain = ambience.rainGain = null;
  }

  function startAmbienceBeds() {
    if (!ambience.ready || !ambienceEnabled || ambience.bedNode) return;
    const a = loopBed(ambience.bed, 0);
    ambience.bedNode = a.src; ambience.bedGain = a.g;
    if (ambience.rainBed) {
      const b = loopBed(ambience.rainBed, 0);
      ambience.rainNode = b.src; ambience.rainGain = b.g;
    }
    refreshAmbienceGains();
  }

  function refreshAmbienceGains() {
    if (!audioCtx) return;
    const t = audioCtx.currentTime;
    const live = soundEnabled && ambienceEnabled;
    const on = live ? ambienceVolume : 0;
    const wet = live ? rainVolume : 0;
    if (ambience.bedGain) ambience.bedGain.gain.setTargetAtTime(on * 0.7, t, 0.4);
    if (ambience.rainGain) {
      // Die Staerke der Wetterfront mal die eingestellte Lautstaerke. Die 0,6 s Glaettung
      // bleiben: sie fangen die Sprunge des Reglers, waehrend die Front die langsame
      // Bewegung macht.
      const lvl = ambience.rainLevel === undefined
        ? (ambience.rainOn ? 1 : 0) : ambience.rainLevel;
      ambience.rainGain.gain.setTargetAtTime(wet * lvl, t, 0.6);
    }
  }

  document.addEventListener('visibilitychange', () => {
    if (document.hidden) stopAmbienceBeds();
    else if (ambienceEnabled) startAmbienceBeds();
    refreshAmbienceGains();
  });

  // The visual side of the weather. Tied to the WEATHER, not to the volume: muting the
  // ambience must not also stop the rain from being visible, or a silent storm becomes an
  // invisible one.
  function setRainVisuals(lvl) {
    const v = typeof lvl === 'number' ? lvl : (lvl ? 1 : 0);
    document.body.classList.toggle('race-wet', v > 0.02);
    // Die Staerke geht als CSS-Variable hinaus, und das Stylesheet entscheidet, was daraus
    // wird: erst wenige Tropfen, dann viele. Die Alternative waere, hier Tropfen zu zaehlen
    // und einzeln zu erzeugen - dann stuende die Gestaltung im Programm.
    document.documentElement.style.setProperty('--rain-lvl', v.toFixed(3));
  }

  // Lightning: two flashes, the second weaker, because real strikes usually double up.
  // Kept very short — 90 ms and 55 ms — so it registers without washing the dash out.
  function triggerLightning() {
    const dash = $('race-dash');
    if (!dash) return;
    const flash = (ms) => {
      dash.classList.add('race-flash');
      setTimeout(() => dash.classList.remove('race-flash'), ms);
    };
    flash(90);
    setTimeout(() => flash(55), 190);
  }

  // STUFE statt Schalter. Vorher war rainOn ein Boolean und die Lautstaerke sprang auf
  // ihren Wert (mit 0,6 s Glaettung im Gain-Knoten); jetzt traegt sie die Staerke der
  // Wetterfront, und der Regen schwillt ueber fuenf Sekunden an.
  //
  // rainOn bleibt als Boolean daneben, weil refreshAmbienceGains() es liest und von
  // mehreren Stellen gerufen wird (Sichtbarkeitswechsel, Lautstaerkeregler). Es ist jetzt
  // "es regnet ueberhaupt", die Staerke steht in rainLevel.
  function setAmbienceRainLevel(lvl) {
    const v = Math.max(0, Math.min(1, lvl || 0));
    ambience.rainLevel = v;
    ambience.rainOn = v > 0.001;
    refreshAmbienceGains();
  }

  // HIER STAND EIN DURCHREICHER setAmbienceRain(on), und die Begruendung daneben war
  // falsch: "der alte Name stand an mehreren Stellen". Er stand an EINER, und die ist bei
  // der Umstellung auf setAmbienceRainLevel mitgezogen. Die Durchsicht auf nicht
  // verdrahtete Teile hat ihn als einzige Funktion ohne Aufruf von 480 gefunden.
  //
  // Eine Behauptung ueber den Code, die man nicht nachgesehen hat, ist schlechter als
  // keine: sie haelt genau die Sache am Leben, die sie rechtfertigt.

  function playAmbienceOneShot(buffer, gain, wet) {
    if (!buffer || !audioCtx || !soundEnabled || !ambienceEnabled || ambience.busy) return;
    ambience.busy = true;                      // never let an event overlap itself
    const src = audioCtx.createBufferSource();
    src.buffer = buffer;
    const g = audioCtx.createGain();
    g.gain.value = gain * (wet ? rainVolume : ambienceVolume);
    const pan = audioCtx.createStereoPanner
      ? audioCtx.createStereoPanner() : null;
    if (pan) {
      pan.pan.value = Math.random() * 1.6 - 0.8;
      src.connect(g).connect(pan).connect(audioCtx.destination);
    } else {
      src.connect(g).connect(audioCtx.destination);
    }
    src.onended = () => { ambience.busy = false; };
    src.start();
  }

  function scheduleAmbienceEvent() {
    // Thunder every 20-30s while it rains (user's spec); otherwise a pass-by every 8-25s.
    // Timing follows the WEATHER, not the audio: the storm exists whether or not the
    // ambience is audible, so the interval must not depend on loaded buffers either.
    const storm = weather === 'rain';
    const wait = storm ? 20000 + Math.random() * 10000 : 8000 + Math.random() * 17000;
    setTimeout(() => {
      if (storm) {
        // Light before sound, the way it actually arrives: the flash fires now, the clap
        // about 200 ms later. The FLASH is outside the audio gate on purpose — muting the
        // ambience must not turn the lightning off as well, or a silent storm becomes an
        // invisible one.
        triggerLightning();
        if (ambience.ready && ambienceEnabled && ambience.thunder.length) {
          const clap = ambience.thunder[Math.floor(Math.random() * ambience.thunder.length)];
          const gain = 0.55 + Math.random() * 0.45;
          setTimeout(() => playAmbienceOneShot(clap, gain, true), 200);
        }
      } else if (ambience.ready && ambienceEnabled && ambience.passby.length) {
        playAmbienceOneShot(ambience.passby[Math.floor(Math.random() * ambience.passby.length)],
                            0.35 + Math.random() * 0.45);
      }
      scheduleAmbienceEvent();
    }, wait);
  }

  function stopSampleEngine() {
    if (!sampleEngine.nodes) return;
    for (const n of sampleEngine.nodes) { try { n.src.stop(); } catch (e) { /* already stopped */ } }
    if (sampleEngine.over) { try { sampleEngine.over.src.stop(); } catch (e) { /* already stopped */ } }
    sampleEngine.nodes = null;
    sampleEngine.over = null;
    sampleEngine.car = null;
    if (sampleEngine.master) sampleEngine.master.gain.setTargetAtTime(0, audioCtx.currentTime, 0.03);
  }

  function startSampleEngine(car) {
    if (!sampleEngine.ready || !sampleEngine.buffers[car]) return false;
    stopSampleEngine();
    if (!sampleEngine.master) {
      sampleEngine.master = audioCtx.createGain();
      sampleEngine.master.gain.value = 0;
      sampleEngine.master.connect(audioCtx.destination);
    }
    // All three start together so they stay phase-consistent for the whole session.
    const t0 = audioCtx.currentTime + 0.04;
    sampleEngine.nodes = BANDS.map(band => {
      const info = sampleEngine.buffers[car][band];
      const src = audioCtx.createBufferSource();
      src.buffer = info.buffer;
      src.loop = true;
      const g = audioCtx.createGain();
      g.gain.value = 0;
      src.connect(g).connect(sampleEngine.master);
      src.start(t0);
      return { src, gain: g, baseRpm: info.baseRpm };
    });
    // The overrun voice runs in PARALLEL to the three power bands, not as a fourth rpm
    // anchor: it is a different operating state, not a different engine speed. One file per
    // engine is enough because it is pitched by rpm exactly like the others.
    const ov = sampleEngine.buffers[car].over;
    if (ov) {
      const src = audioCtx.createBufferSource();
      src.buffer = ov.buffer;
      src.loop = true;
      const g = audioCtx.createGain();
      g.gain.value = 0;
      src.connect(g).connect(sampleEngine.master);
      src.start(t0);
      sampleEngine.over = { src, gain: g, baseRpm: ov.baseRpm };
    }
    sampleEngine.car = car;
    if (engineGain) engineGain.gain.setTargetAtTime(0, audioCtx.currentTime, 0.05); // hush the oscillator
    return true;
  }

  // Triangular crossfade between the three anchors. The weights always sum to exactly 1,
  // so moving through the rev range can never produce a hole or a bulge in loudness.
  function sampleWeights(rpm, b) {
    const w = [0, 0, 0];
    if (rpm <= b[0]) w[0] = 1;
    else if (rpm >= b[2]) w[2] = 1;
    else if (rpm <= b[1]) { const t = (rpm - b[0]) / (b[1] - b[0]); w[0] = 1 - t; w[1] = t; }
    else { const t = (rpm - b[1]) / (b[2] - b[1]); w[1] = 1 - t; w[2] = t; }
    return w;
  }

  // Doppler at the line. A trackside listener hears an approaching car high and a
  // departing one low, and the crossing is where the sign flips. The physical ratio at
  // scale speed would be about 1.6 either way, which is what a real flyby sounds like and
  // completely absurd for a sound the driver hears continuously — so the swing is scaled by
  // speed and capped well below the physical value. It is a cue, not a simulation.
  const DOPPLER_MAX = 0.10;      // +-10 % at the top of the speed range
  const DOPPLER_S = 0.45;        // how long the sweep takes
  let dopplerStart = 0;
  function triggerDoppler() {
    if (!sampleEngine.nodes || !audioCtx) return;
    dopplerStart = audioCtx.currentTime;
  }
  function dopplerFactor() {
    if (!dopplerStart || !audioCtx) return 1;
    const u = (audioCtx.currentTime - dopplerStart) / DOPPLER_S;
    if (u < 0 || u > 1) { dopplerStart = 0; return 1; }
    const frac = Math.min(1, Math.abs(physEngine.state.speedKmh) / physEngine.config.topSpeedKmh);
    // cos over the window: starts high, passes through unity at the middle, ends low.
    return 1 + Math.cos(u * Math.PI) * DOPPLER_MAX * frac;
  }

  function updateSampleEngine(rpm, load, silent) {
    const nodes = sampleEngine.nodes;
    const scale = sampleEngine.rpmScale[sampleEngine.car] || 1;
    // The crossfade has to see the same scaled rpm as the playback rate does, otherwise the
    // band boundaries and the pitch disagree and you hear the wrong loop at the wrong speed.
    const w = sampleWeights(rpm * scale, nodes.map(n => n.baseRpm));
    const t = audioCtx.currentTime;
    // How much of the power sound against the overrun sound. Closed at a trace of throttle
    // rather than at exactly zero, because a real engine is back on the gas well before the
    // pedal is fully down, and a crossfade that only completes at load = 0 spends most of
    // its travel doing nothing audible.
    const over = sampleEngine.over;
    const powerMix = over ? Math.min(1, Math.max(0, (load - 0.06) / 0.30)) : 1;
    const dop = dopplerFactor();
    nodes.forEach((n, i) => {
      // A loop generated at baseRpm played back at rpm/baseRpm IS that engine speed.
      // Clamped because resampling much beyond an octave stops sounding like an engine —
      // past that the neighbouring loop has taken over anyway.
      const rate = Math.max(0.5, Math.min(2.0, rpm * scale / n.baseRpm * dop));
      n.src.playbackRate.setTargetAtTime(rate, t, 0.04);
      n.gain.gain.setTargetAtTime(w[i] * powerMix, t, 0.05);
    });
    if (over) {
      const rate = Math.max(0.5, Math.min(2.0, rpm * scale / over.baseRpm * dop));
      over.src.playbackRate.setTargetAtTime(rate, t, 0.04);
      over.gain.gain.setTargetAtTime(1 - powerMix, t, 0.05);
    }
    // With a real overrun loop the master no longer has to fake off-throttle by turning
    // down — the quieter, crackling sound does that itself. Ducking it as hard as before
    // would just hide the loop that was made for this.
    let vol = engineVolume * (over ? 0.55 + 0.45 * load : 0.25 + 0.75 * load);
    if (physEngine.state.onLimiter) vol *= 0.8 + 0.2 * Math.sign(Math.sin(Date.now() / 18));
    sampleEngine.master.gain.setTargetAtTime(silent ? 0 : vol, t, 0.05);
  }

  $('sound-profile').addEventListener('change', (e) => {
    const v = e.target.value;
    if (SAMPLE_CARS.includes(v)) {
      if (!startSampleEngine(v)) {
        // Schleifen noch nicht geladen: das ist normal und kein Fehler, sie kommen
        // asynchron. Der Rueckfall ist hier voruebergehend.
        soundProfile = SOUND_PROFILES.v8;
        if (engineOsc) engineOsc.type = soundProfile.wave;
      }
      return;
    }
    // HIERHER darf ein Menueeintrag nicht mehr kommen. Seit v0.5 sind alle 17 Eintraege
    // Schleifenmotoren, und wer hier landet, hat einen Wert ohne Schleifen - genau der
    // Fehler, der den Porsche 911 GT3 R vier Wochen lang als Saegezahn spielen liess.
    // Still zurueckzufallen hat ihn versteckt, also wird es jetzt gemeldet.
    stopSampleEngine();
    soundProfile = SOUND_PROFILES[v] || SOUND_PROFILES.v8;
    if (engineOsc) engineOsc.type = soundProfile.wave;
    log('Motorprofil "' + v + '" hat keine Schleifen, Ersatzmotor laeuft. Das ist ein '
        + 'Fehler, wenn der Eintrag im Menue steht.', 'warn');
  });

  $('cm-start').addEventListener('click', () => {
    cmOn = !cmOn;
    $('cm-start').textContent = cmOn ? 'Z\u00e4hlen stoppen' : 'Z\u00e4hlen starten';
    $('cm-start').classList.toggle('warn', cmOn);
    if (cmOn) cmReset();
    log('Rohcode-Monitor ' + (cmOn ? 'an' : 'aus') + '.', 'info');
  });
  $('cm-reset').addEventListener('click', cmReset);

  $('lat-hold').addEventListener('change', (e) => {
    $('lat-hold-lbl').textContent = String(parseInt(e.target.value, 10) / 1000);
  });
  $('lat-start').addEventListener('click', () => {
    if (lat.on) { latStop('von Hand beendet'); return; }
    const car = playerCar || garage.find(c => c.rx);
    if (!car) { log('Querablage-Messung: kein Auto verbunden.', 'err'); return; }
    // Der Ghost-Fahrer wuerde gegen die Messung senden. Er wird angehalten, nicht
    // uebertoent - zwei Sender auf einem Auto heisst, dass jedes zweite Paket etwas
    // anderes will.
    stopGhost(car);
    lat.on = true; lat.car = car; lat.step = 0; lat.tiles = 0; lat.lastCount = null;
    lat.rows = [];
    lat.dir = parseInt($('lat-dir').value, 10);
    lat.steer = 0;
    lat.stepAt = Date.now();
    $('lat-start').textContent = 'Messung stoppen';
    $('lat-start').classList.add('warn');
    latRender();
    log('Querablage-Messung laeuft mit ' + garageLabel(car) + '. Gas '
        + $('lat-throttle').value + ', Stufe ' + $('lat-inc').value + ', Haltezeit '
        + (parseInt($('lat-hold').value, 10) / 1000) + ' s.', 'info');
    if (lat.timer) clearInterval(lat.timer);
    lat.timer = setInterval(latTick, CONTROL_SEND_INTERVAL_MS);
  });
  $('lat-off').addEventListener('click', () => latCommit(false));
  $('lat-hold-here').addEventListener('click', () => { lat.stepAt = Date.now(); latRender(); });
  $('lat-reset').addEventListener('click', () => { lat.rows = []; lat.tiles = 0; latRender(); });

  $('ghost-spice').addEventListener('input', (e) => {
    ghostCfg.spice = parseFloat(e.target.value);
    $('ghost-spice-val').textContent = ghostCfg.spice === 0
      ? 'aus' : Math.round(ghostCfg.spice * 100) + '%';
  });

  $('ghost-line').addEventListener('input', (e) => {
    ghostCfg.line = parseFloat(e.target.value);
    $('ghost-line-val').textContent = ghostCfg.line === 0
      ? 'aus' : Math.round(ghostCfg.line * 100) + '%';
  });

  $('tyre-volume').addEventListener('input', (e) => {
    tyreVolume = parseFloat(e.target.value);
    $('tyre-volume-val').textContent = tyreVolume === 0
      ? 'aus' : Math.round(tyreVolume * 100) + '%';
  });

  $('setting-tyre-blankets').addEventListener('change', (e) => {
    physEngine.config.tyreBlankets = e.target.checked;
    log('Reifenwaermer ' + (e.target.checked ? 'an: Start und Wechsel auf '
        + physEngine.config.tyreOptimalC + ' Grad' : 'aus: Start und Wechsel kalt') + '.', 'info');
  });

  $('ghost-lanes').addEventListener('input', (e) => {
    ghostCfg.lanes = parseFloat(e.target.value);
    $('ghost-lanes-val').textContent = ghostCfg.lanes === 0
      ? 'aus' : Math.round(ghostCfg.lanes * 100) + '%';
  });

  $('ghost-learn').addEventListener('change', (e) => {
    ghostCfg.learn = e.target.checked;
    if (!e.target.checked) learnReset();
    log('Streckenlernen ' + (e.target.checked ? 'an' : 'aus') + '.', 'info');
  });

  $('ghost-needcode').addEventListener('change', (e) => {
    ghostCfg.needCode = e.target.checked;
    log('Ghost ' + (e.target.checked ? 'braucht' : 'braucht keinen') + ' Streckencode.', 'info');
  });

  $('setting-rain').addEventListener('change', (e) => {
    setWeather(e.target.checked ? 'rain' : 'dry');
  });

  $('amb-enable').addEventListener('change', (e) => {
    ambienceEnabled = e.target.checked;
    if (ambienceEnabled) startAmbienceBeds(); else stopAmbienceBeds();
    refreshAmbienceGains();
  });

  $('amb-volume').addEventListener('input', (e) => {
    ambienceVolume = parseFloat(e.target.value);
    $('amb-volume-val').textContent = Math.round(ambienceVolume * 100) + '%';
    refreshAmbienceGains();
  });

  // Both models fade to nothing at the left end, so "off" is genuinely the old behaviour
  // rather than a very small amount of the new one.
  $('ghost-rail').addEventListener('change', (e) => {
    ghostCfg.railMode = e.target.checked;
  });

  // renderGarage() wird mitgerufen: sonst zeigt die Garagenzeile weiter die alte Zahl,
  // obwohl die Vorgabe sich geaendert hat - und die Zeile ist genau die Stelle, an der man
  // nachsieht, ob es gewirkt hat.
  $('ghost-speed').addEventListener('input', (e) => {
    ghostCfg.speed = parseFloat(e.target.value);
    $('ghost-speed-val').textContent = Math.round(ghostCfg.speed * 100) + '%';
    if (typeof renderGarage === 'function') renderGarage();
  });
  $('ghost-curve').addEventListener('input', (e) => {
    ghostCfg.curveSlow = parseFloat(e.target.value);
    $('ghost-curve-val').textContent = Math.round(ghostCfg.curveSlow * 100) + '%';
  });
  $('ghost-lateral').addEventListener('input', (e) => {
    ghostCfg.lateral = parseFloat(e.target.value);
    $('ghost-lateral-val').textContent = ghostCfg.lateral === 0
      ? 'aus' : Math.round(ghostCfg.lateral * 100) + '%';
  });
  $('ghost-leader').addEventListener('change', (e) => {
    ghostCfg.leaderBrake = e.target.checked;
  });

  $('ghost-leader-pct').addEventListener('input', (e) => {
    ghostCfg.leaderBrakePct = parseFloat(e.target.value);
    $('ghost-leader-pct-val').textContent = Math.round(ghostCfg.leaderBrakePct * 100) + '%';
  });

  $('setting-fuelweight').addEventListener('input', (e) => {
    const v = parseFloat(e.target.value);
    physEngine.config.fuelWeightEffect = v;
    $('setting-fuelweight-val').textContent = v === 0 ? 'aus' : Math.round(v * 100) + '%';
  });

  $('setting-tyres').addEventListener('input', (e) => {
    const v = parseFloat(e.target.value);
    physEngine.config.tyreEffect = v;
    $('setting-tyres-val').textContent = v === 0 ? 'aus' : Math.round(v * 100) + '%';
    if (v === 0) resetTyres();   // leave nothing stale behind when switching off
  });

  $('brake-volume').addEventListener('input', (e) => {
    brakeVolume = parseFloat(e.target.value);
    $('brake-volume-val').textContent = Math.round(brakeVolume * 100) + '%';
  });

  $('rain-volume').addEventListener('input', (e) => {
    rainVolume = parseFloat(e.target.value);
    $('rain-volume-val').textContent = Math.round(rainVolume * 100) + '%';
    refreshAmbienceGains();
  });

  $('sound-volume').addEventListener('input', (e) => {
    engineVolume = parseFloat(e.target.value);
    $('sound-volume-val').textContent = Math.round(engineVolume * 100) + '%';
  });

  // Pitch follows engine RPM, volume follows pedal opening. Because triggerShift() moves
  // the gear immediately while isShifting only clears later, the revs drop on the very
  // same tick — so the note audibly falls at each upshift and climbs again, instead of
  // rising monotonically with road speed as it used to.
  let engineIdleSince = null;
  function updateEngineSound(throttleMagnitude) {
    if (!soundEnabled || !engineOsc) return;
    const st = physEngine.state, p = soundProfile;
    let pitchNorm, load;
    if (physicsEnabled) {
      pitchNorm = st.rpmFrac;
      load = st.engineLoad;
    } else {
      pitchNorm = load = Math.abs(throttleMagnitude); // raw mode: unchanged behaviour
    }
    // RPM never drops below idle, so without this the engine would hum forever after load.
    const busy = load > 0.01 || st.virtualSpeed > 0.01;
    const now = Date.now();
    if (busy) engineIdleSince = null;
    else if (engineIdleSince === null) engineIdleSince = now;
    const silent = !busy && engineIdleSince !== null && now - engineIdleSince > 4000;

    // Sample engine takes over when a car is loaded and playing; the oscillator path below
    // stays intact as the fallback for the synthetic profiles and for missing audio/.
    // Squeal only under real braking above walking pace, so it does not chirp on every
    // light touch of the trigger.
    const brakeAmt = (physicsEnabled && st.speedKmh > physEngine.config.topSpeedKmh * 0.12)
      ? Math.max(0, Math.min(1, (Math.max(0, -throttleY) - 0.25) / 0.55)) : 0;
    setBrakeSqueal(brakeAmt);
    // Der Reibkreis-Querbedarf treibt es. Er steht im Zustand, weil er hier gebraucht wird.
    setTyreSqueal(physEngine.state.latUse || 0);

    if (sampleEngine.nodes && physicsEnabled) { updateSampleEngine(st.rpm, load, silent); return; }

    const freq = p.baseFreq + Math.max(0, Math.min(1, pitchNorm)) * p.freqSpan;
    let gain = p.gainBase * (0.35 + 0.65 * pitchNorm) + load * p.gainSpan;
    if (st.onLimiter) gain *= 0.75 + 0.25 * Math.sign(Math.sin(now / 18)); // limiter flutter
    if (silent) gain = 0;
    const t = audioCtx.currentTime;
    engineOsc.frequency.setTargetAtTime(freq, t, 0.03); // 0.03: don't smear the shift drop
    engineGain.gain.setTargetAtTime(gain, t, 0.05);
  }

  // Short synthesized impact: a burst of white noise through a fast decay envelope.
  function playCrashSound() {
    if (!soundEnabled || !audioCtx) return;
    const dur = 0.45;
    const buffer = audioCtx.createBuffer(1, Math.floor(audioCtx.sampleRate * dur), audioCtx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < data.length; i++) {
      data[i] = (Math.random() * 2 - 1) * (1 - i / data.length); // noise, decaying
    }
    const src = audioCtx.createBufferSource();
    src.buffer = buffer;
    const g = audioCtx.createGain();
    const t = audioCtx.currentTime;
    g.gain.setValueAtTime(0.5, t);
    g.gain.exponentialRampToValueAtTime(0.001, t + dur);
    const lp = audioCtx.createBiquadFilter();
    lp.type = 'lowpass';
    lp.frequency.setValueAtTime(1200, t);
    src.connect(lp).connect(g).connect(audioCtx.destination);
    src.start();
    src.stop(t + dur);
  }

  let hudToastTimer = null;
  function showHudToast(msg) {
    const el = $('hud-toast');
    if (!el) return;
    el.textContent = msg;
    clearTimeout(hudToastTimer);
    if (msg) hudToastTimer = setTimeout(() => { el.textContent = ''; }, 1500);
  }

  refreshTrackPreview();

